name: Continuous Integration

on:
  push:
    tags-ignore:
    - 'v*'
    branches:
    - "**"
  pull_request:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  ci:
    uses: smallstep/workflows/.github/workflows/goCI.yml@main
